[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Hotel-Id = "HVH-7788"
    X-Repo-Env = "production"